# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://ejwillemse.github.io."
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
# baseurl:

# Title of the Site
title: A Heuristic Life
# Description of the Site
description: My personal website :-) still very much a work in progress...
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
# email: elias@heuristic.life
# facebook_username: thedevslot
# twitter_username: thedevslot
# instagram_username: thedevslot
linkedin_username: eliasjw
# github_username: thedevslot
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Elias J. Willemse
# URL for the Image of the Author
author-image: /assets/images/Elias_blazer_blw_sml_less1mb.jpg
# 60 Words About the Author
author-about: I'm a technical founder, based in London, with over 15 years of hands-on experience in AI and data science. Getting to this point took a while, via a PhD, being a senior lecturer, research fellow, engineering consultant, and moving from South Africa (most of my life) to Singapore (4 years) and now London (since 2022).
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
# author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-toc

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  - scope:
      type: "posts"
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  - scope:
      type: "pages"
    values:
      layout: page

toc:
  min_level: 2 # default: 1
  max_level: 2 # default: 6

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - test-page.md
  - about.md
  - blog.md
